import type { Metadata } from 'next';
import { ArrowRight, Check } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Editorial guidelines',
  description: 'How audioplugin.io documents audio software history, reviews submissions, and corrects the record.',
  alternates: { canonical: '/editorial-guidelines' },
};

export default function EditorialGuidelinesPage() {
  return <main className="policy-page"><header className="record-header"><a className="wordmark" href="/"><span className="mark">A</span><span>audioplugin.io</span><small>archive</small></a><nav><a href="/">Archive</a><a href="/status/discontinued">Discontinued</a><a href="/submit">Submit a plugin</a></nav></header><section className="policy-hero"><p className="eyebrow">Editorial standards</p><h1>Keep the record<br/><em>useful and fair.</em></h1><p>audioplugin.io is an independent historical archive. Entries are selected for their factual value—not through payment, sponsorship, or placement.</p></section><section className="policy-content"><article><section><h2>What belongs in the archive</h2><p>We document released audio software: virtual instruments, effects, hosts, DAWs, utilities, and related production tools. An entry should identify the product, its developer, its release context, and the sources that support its claims.</p><ul><li><Check size={16}/> Release dates and version numbers should be supported by a primary or reliable historical source.</li><li><Check size={16}/> Product descriptions should explain what the software did, without marketing claims presented as fact.</li><li><Check size={16}/> Discontinued products remain valuable records and are clearly labelled as archived.</li></ul></section><section><h2>How entries are reviewed</h2><p>Submissions and proposed edits are reviewed before publication. We prefer official documentation, manuals, dated announcements, and developer pages. When only secondary historical material survives, we identify the source so readers can judge it for themselves.</p></section><section><h2>Corrections and disagreements</h2><p>Historical software records can be incomplete or contradictory. When credible evidence changes a date, format, developer attribution, or product status, we update the entry and preserve source links. Use the plugin submission form to send a correction with supporting material.</p></section></article><aside><p className="eyebrow">Editorial principles</p><h2>Evidence before hype.</h2><p>We distinguish between documented facts, developer statements, and incomplete history.</p><a className="entry-link" href="/sources-policy">Read the sources policy <ArrowRight size={15}/></a><a className="entry-link" href="/submit">Suggest a correction <ArrowRight size={15}/></a></aside></section></main>;
}
